name: "USB-Construct Tests"
on:
  push:
    branches:
      - 'main'
  pull_request: {}

jobs:
  test-usbconstruct:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]
      fail-fast: false

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Initialize Env
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH
          echo "GITHUB_WORKSPACE=\"`pwd`\"" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        shell: bash
        run: |
          sudo apt-get update
          python -m pip install --user --upgrade pip setuptools wheel setuptools_scm nox


      - name: Run Tests
        shell: bash
        run: |
          nox -s test -- --coverage

      - name: Codecov Upload
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          files: ./build/tests/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
